config/routes.rb
Amapp::Application.routes.draw do
  resources :items do
    member do
      get 'plot'
    end
    resources :price_records
  end

  get "home/index"

root :to => "home#index"

end

app/models/item.rb
require 'rubygems'
require 'amazon/aws/search'
include Amazon::AWS

class Item < ActiveRecord::Base
  attr_protected :title

  validates_uniqueness_of :asin
  validate :is_valid_asin

private
  # Make an item lookup request using Amazon's API with the ASIN. Exceoptions
  # are not caught in this method.
  def get_item(rg)
    il = ItemLookup.new( 'ASIN', { 'ItemId' => self.asin,
                           'MerchantId' => 'Amazon' } )
    il.response_group = rg
    req = Search::Request.new()

    return req.search(il)
  end

  # Check if the ASIN is a valid Amazon item and set title if it is.
  def is_valid_asin
    rg = ResponseGroup.new(:Small)
    begin
      resp = get_item(rg)
      item = resp.item_lookup_response[0].items[0].item
      self.title = item.item_attributes.title.to_s
    rescue Error::InvalidParameterValue
      errors.add(:asin, "Invalid ASIN")
      return false
    end
    return true
  end
end

app/models/price_record.rb
require 'rubygems'
require 'amazon/aws/search'
include Amazon::AWS

class PriceRecord < ActiveRecord::Base
  belongs_to :item

  after_validation :set_item_price

private
  # Make an item lookup request using Amazon's API with the ASIN. Exceoptions
  # are not caught in this method.
  def get_item(rg)
    il = ItemLookup.new( 'ASIN', { 'ItemId' => self.item.asin,
                           'MerchantId' => 'Amazon' } )
    il.response_group = rg
    req = Search::Request.new()

    return req.search(il)
  end

  # Check if the ASIN is a valid Amazon item and set title if it is.
  def set_item_price
    rg = ResponseGroup.new('Offers', 'ItemAttributes')
    begin
      resp = get_item(rg)
      item = resp.item_lookup_response[0].items[0].item
    rescue Error::InvalidParameterValue
      errors.add(:asin, "Invalid ASIN")
    end
    begin
      self.amount = item.offers.offer.offer_listing.price.amount
    rescue NoMethodError
      self.amount = item.item_attributes.list_price.amount
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.xml
  def index
    @items = Item.all.sort_by &:title

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @items }
    end
  end

  # GET /items/1
  # GET /items/1.xml
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/1/plot
  # GET /items/1/plot.xml
  def plot
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item.price_records }
    end
  end

  # GET /items/new
  # GET /items/new.xml
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # POST /items
  # POST /items.xml
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to(@item, :notice => 'Item was successfully created.') }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.xml
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to(@item, :notice => 'Item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.xml
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to(items_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/price_records_controller.rb
class PriceRecordsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @price_record = @item.price_records.create(params[:price_record])
    redirect_to item_path(@item)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/price_records_helper.rb
module PriceRecordsHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<%= link_to "Tracked items", items_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asin %><br />
    <%= f.text_field :asin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Asin</th>
   <th></th>
  </tr>

  <% @items.each do |item| %>
  <tr>
    <td><%= link_to item.title, item %></td>
    <td><%= item.asin %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/plot.html.erb
<%= javascript_include_tag "dygraph-combined" %>

<div id="graphdiv"></div>
<script type="text/javascript">
  g = new Dygraph(
    document.getElementById("graphdiv"),
    "Date,Price\n" +
    <% length = @item.price_records.length %>
    <% plus = ' +' %>
    <% for i in 0..length-1 %>
      <% price_record = @item.price_records[i] %>
      <% if i == length-1;  plus = ''; end %>
      "<%= price_record.created_at %>,<%= Float(price_record.amount)/100 %>\n"<%= plus %>
    <% end %>
  );
</script>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Asin:</b>
  <%= @item.asin %>
</p>

<p>
  <b>Title:</b>
  <a href='http://www.amazon.com/gp/product/<%= @item.asin %>'><%= @item.title %></a>
</p>

<h2>Price Records</h2>
<table>
  <tr>
    <th>Amount</th>
    <th>Recorded at:</th>
  </tr>

  <% @item.price_records.each do |price_record| %>
  <tr>
    <td>$<%= '%.2f' % (Float(price_record.amount)/100) %></td>
    <td><%= price_record.created_at %></td>
  </tr>
  <% end %>
</table>

<h2>Record Price (<%= link_to 'plot', plot_item_path %>)</h2>
<%= form_for([@item, @item.price_records.build]) do |f| %>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amapp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>